# Generated by Django 4.1.2 on 2024-10-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuarios_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user_profile_image',
            field=models.ImageField(upload_to='Perfil'),
        ),
    ]
