# Generated by Django 4.1.2 on 2024-10-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuarios_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
