# Generated by Django 4.1.2 on 2024-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
