# Generated by Django 4.1.2 on 2024-10-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_producto_cod_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(max_length=100),
        ),
    ]
