# Generated by Django 5.1.2 on 2024-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_producto_imagen_alter_producto_cod_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='productos/'),
        ),
    ]
