# Generated by Django 5.1.2 on 2024-10-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_categoria_referencia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='referencia_categoria',
            field=models.CharField(max_length=20),
        ),
    ]
