# Generated by Django 5.1.2 on 2024-10-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_categoria_referencia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.CharField(max_length=30),
        ),
    ]
