# Generated by Django 5.1.2 on 2024-10-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ventas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='nombre',
            new_name='referencia',
        ),
    ]
