# Generated by Django 5.1.2 on 2024-10-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
