# Generated by Django 5.1.3 on 2024-12-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_horario_nomina_cotizaciones_total_producto_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='detallecotizaciones',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='detallecotizaciones',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Nomina',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Cotizaciones',
        ),
        migrations.DeleteModel(
            name='DetalleCotizaciones',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Devoluciones',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
